import { Projects } from "../types/projects";

export const projectList: Projects = [
    {
      title: 'Basket Maniacs Web App',
      subtitle: 'Angular/RxJs/Material',
      imgSrc: './assets/img/bm.jpg',
      desc: 'A SPA dedicated to NBA fans showing latest news, scores, info about teams and players. Uses Angular Material, services and RxJs operators to elaborate data received from remote APIs. I\'m continuously improving it.',
      designUrl: 'https://www.figma.com/file/zXa5Q8IpAgz19Uqle2R4NH/Serwis-NBA?type=design&node-id=0%3A1&mode=design&t=QtLDPxJ0HFTGQ87l-1',
      gitUrl: 'https://gitlab.com/franckyiside/nba-app',
      liveUrl: 'https://francky.works/basket-maniacs',
    },
    {
      title: 'Seconds Formatter',
      subtitle: 'JavaScript',
      imgSrc: './assets/img/seconds.jpg',
      desc: 'Guess how many days are one million seconds? Don\'t know? Check it with this mini tool. It\'ll return the answer in a readable, human-friendly format.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/seconds-formatter',
      liveUrl: 'https://francky.works/seconds-formatter/',
    },
    {
      title: 'Weather Web App',
      subtitle: 'JavaScript',
      imgSrc: './assets/img/weather-js.jpg',
      desc: 'A weather app with dynamically changing background image basing on your current weather. Thanks to HTML5 Geolocation API retrieves weather info for local or remote position. OpenWeather API provides the weather info, which I integrated with Pexels API to change the images.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/weather-app-vanilla-js',
      liveUrl: 'https://francky.works/weather-app',
    },
    {
      title: 'Godere Website',
      subtitle: 'Angular/Ng Bootstrap',
      imgSrc: './assets/img/godere.jpg',
      desc: 'Godere specialises in building highly performant gaming computers and workstations. But with a particularity: the cases are built on the top of 1000+ LEGO pieces!',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/godere',
      liveUrl: 'https://en.godere.pl/',
    },
    {
      title: 'Lantu Website',
      subtitle: 'Angular/Material',
      imgSrc: './assets/img/lantu.jpg',
      desc: 'Lantu imports for you original and natural products from Madagascar. The simple frontpage to deliver more information about the products.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/lantu',
      liveUrl: 'https://lantu.pl',
    },
    {
      title: 'Weather Web App',
      subtitle: 'Angular/Material',
      imgSrc: './assets/img/weather-angular.jpg',
      desc: 'Angular version of the weather app. I\'ve had a taste of Vue and React doing this same application. Check them on my GitLab profile.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/weather-app',
      liveUrl: 'https://francky.works/weather-app-angular',
    },
    {
      title: 'G-BIZ Website',
      subtitle: 'Bootstrap',
      imgSrc: './assets/img/gbiz.jpg',
      desc: 'G-BIZ offers accounting services in the Trójmiasto area. The website is a base for all the info clients need before contacting.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/g-biz-website',
      liveUrl: 'http://g-biz.pl',
    },
    {
      title: 'Daddy\'s E-commerce',
      subtitle: 'WordPress/WooCommerce',
      imgSrc: './assets/img/daddys.jpg',
      desc: 'For Daddy\'s I designed and developed a custom WordPress theme. I was also involved in the creation of the graphics, creation and setup of products, categories and other things related to an e-commerce. Lastly I started the development on the top of the design I created with Figma.',
      designUrl: 'https://www.figma.com/file/IAJYrobSn8iRPy3q6J6boO/Daddys-ecommerce?type=design&mode=design&t=hSwubaL4lxEmMaJE-1',
      gitUrl: null,
      liveUrl: 'https://daddys.pl/',
    },
    {
      title: 'Wedding Website',
      subtitle: 'HTML5/SASS/JavaScript',
      imgSrc: './assets/img/wedding.jpg',
      desc: 'Tiffania and Justin needed a web page to provide guests more info about their wedding. I came to help developing a simple, elegant and fully responsive website featuring a JavaScript countdown to the date and every info guests may need to reach the locations.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/wedding-website',
      liveUrl: 'https://justinandtiffania.com/',
    },
    {
      title: 'Color Themes for VSC',
      subtitle: 'JSON/NPM',
      imgSrc: './assets/img/vsc.jpg',
      desc: 'A pack of color themes for Visual Studio Code inspired by popular developer tools. It currently includes colors of Angular Material Doc and Firefox DevTools. Install the extension "DevThemes pack" directly from VSC extensions or download it online on Microsoft VSC marketplace.',
      designUrl: null,
      gitUrl: 'https://gitlab.com/franckyiside/vsc-devthemes',
      liveUrl: 'https://marketplace.visualstudio.com/publishers/FranckyIside',
    }
]